# Generated by Django 4.0.6 on 2023-02-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
