# Generated by Django 4.0.6 on 2023-02-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_products_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
