# Generated by Django 4.0.6 on 2023-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_products_numreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
